### ISSUE TITLE
Difficulties with more than one service per app

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docker#102]
It is difficult to use this runtime to deploy more than one service per app to AppEngine, due to the requirement of each service to share `nginx-app.conf` `php.ini` and `supervisord.conf` files.

We could add a `runtime_config` variable `conf_dir` that can be used to change the configuration dir from the default (`/app`) to something else (like `/app/config/my_service`)

**Comment by bshaffer** [comment]
It would also be great if changing `endpoint` in `app.yaml` from `endpoint.sh` would bypass starting NGINX/php-fpm

**Comment by tmatsuo** [comment]
This docker image doesn't know anything about `runtime_config`. It's solely implemented by the gcloud SDK.

Anyways we have `Dockerfile` limitation.

Can you create another directory for another service?

> It would also be great if changing endpoint in app.yaml from endpoint.sh would bypass starting NGINX/php-fpm

It is also gcloud SDK's responsibility to change CMD in the generated Dockerfile.

**Comment by bshaffer** [comment]
I assumed since `document_root` gets passed in as `$DOCUMENT_ROOT`, then something else could get passed in as well. Are you saying `document_root` is a whitelisted config value in `gcloud`?

**Comment by tmatsuo** [comment]
For user supplied `php.ini`, it's implemented by the `--configure` option of PHP.

```
--with-config-file-scan-dir=$APP_DIR
```

For other user-supplied configuration files, we can introduce something like `USER_CONF_DIR` defaults to `/app`.


However, I still don't think it's warrant to introduce more complexity into the docker image. It can be implemented in gcloud SDK layer.

**Comment by bshaffer** [comment]
How do we decide which directives are right for gcloud, and which are right for this image? Anything not specific to `app.yaml` would go here, so this image can be usable in other contexts (kubernetes, etc).

**Comment by tmatsuo** [comment]
OK. How about to introduce few environment variables; APP_NGINX_ADDITIONAL_CONF, APP_NGINX_CONF, and PHP_FPM_CONF_OVERRIDE?

**Comment by tmatsuo** [comment]
When those environment variables are available, we can prefix ${APP_DIR}/ and just use the values. For example, you can specify different nginx-app.conf with the following yaml files.

app.yaml
```
runtime: php
vm: true

runtime_config:
  document_root: web
```
Then APP_NGINX_ADDITIONAL_CONF falls back to '/app/nginx-app.conf' for this service.

worker.yaml
```
runtime: php
vm: true
service: worker

runtime_config:
  document_root: web
env_variables:
  APP_NGINX_ADDITIONAL_CONF: config/worker-nginx-app.conf
``` 

Then the runtime looks for '/app/config/worker-nginx-app.conf'

How does it sound?

**Comment by bshaffer** [comment]
This sounds good! Would we also have `APP_SUPERVISORD_CONF` and `APP_PHP_INI_CONF`?
