### ISSUE TITLE
Use stable php-cs-fixer

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docker#111]
We can just use the phar, but it's better to install it via composer with an explicit version.

**Comment by keradus** [comment]
Hi @tmatsuo  ;)

I would use composer, but if you want you could download specific phar version as well, eg `http://get.sensiolabs.org/php-cs-fixer-v1.11.4.phar`

**Comment by tmatsuo** [comment]
Hey @keradus 
Thanks for the tips!

**Comment by keradus** [comment]
always pleasure to work with you ;)

**Comment by tmatsuo** [comment]
http://get.sensiolabs.org/php-cs-fixer-v1.11.4.phar failed to run with the following error on our jenkins server:
```
PHP Parse error:  syntax error, unexpected 'self' (T_STRING) in phar:///var/lib/jenkins/bin/php-cs-fixer/vendor/symfony/process/Process.php on line 538
```

**Comment by keradus** [comment]
Could you check 1.11.3 please?

**Comment by tmatsuo** [comment]
Yeah 1.11.3 works fine

**Comment by keradus** [comment]
I feel that I will have some nice debugging...
one way or another thanks for report (ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1968), it won't be ignored! (just maybe not obvious to fix)

Do you have any bigger crash log ?

**Comment by tmatsuo** [comment]
No, but it turned out that the PHP on one of our jenkins server is 5.4.45 from the wheezy distribution! We should definitely upgrade :)

**Comment by tmatsuo** [comment]
Ok, now we're using 1.11.3 and it works

**Comment by keradus** [comment]
@tmatsuo 
We decided to move phar files to github Releases.
Please, could you check this phar file: https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v1.11.4 on your env ?

If you confirm this then it means that we have working PR for https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1968

**Comment by bshaffer** [comment]
@keradus we switched to using composer to pull this in (#115), so I'm not sure us changing to `1.11.4` will actually test what you expect.

**Comment by keradus** [comment]
ref https://github.com/GoogleCloudPlatform/php-docker/issues/111#issuecomment-224297453

could new phar file (from github, not sensiolabs) could be tested on that env where it failed before ?
