### ISSUE TITLE
[RFC] PHP 7.1

### ISSUE THREAD

**Issue by cedricziel** [GoogleCloudPlatform/php-docker#130]
[PHP 7.1 beta1 was released](http://php.net/archive/2016.php#id2016-07-21-1) :tada: 

Would you accept a pull request with a third runtime version?

**Comment by tmatsuo** [comment]
Yes! We moved the test run to CircleCI a while ago. Let me check if tests for PRs from other repos just work.

**Comment by tmatsuo** [comment]
Yeah it worked. Feel free to send us a PR :)

**Comment by tmatsuo** [comment]
I hope we will have PHP 7.1 soon. Related #173
