### ISSUE TITLE
Adds guides for running PHP frameworks/PHP products

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docker#140]
The reason I wanted to add this info to [our documentation](https://cloud.google.com/php) is due to the inefficiency on reviewing the document PR on this repo, CircleCI will run our full tests for each edit. Also If we add it, I want to also add tests for that because such information can be easily become stale.

I still want to add such documentation and tests to other places; docs on https://cloud.google.com/php and tests in php-docs-samples.

**Comment by bshaffer** [comment]
agreed! The doc site is a better place for this, as long as we link to the docs from the README

**Comment by bshaffer** [comment]
This is being tracked elsewhere, and doesn't really belong in this repo.
