### ISSUE TITLE
Switch from using local docker to Container Builder

### ISSUE THREAD

**Issue by dlorenc** [GoogleCloudPlatform/php-docker#148]

**Comment by tmatsuo** [comment]
The build script is already using Container Builder when possible.

**Comment by dlorenc** [comment]
We can track this in another issue if you like, but I think the PHP runtime still uses docker to pull/tag/push. This is now possible with gcloud beta container images add-tag, which doesn't need container builder or docker.

Would you mind switching to that? I'd like to disable docker on the build server if possible.

**Comment by tmatsuo** [comment]
Oh I see.

**Comment by tmatsuo** [comment]
We're also running various tests with local docker. I think we should migrate those tests to container builder to remove dependency on local docker.

**Comment by tmatsuo** [comment]
Now almost everything is running on cloudbuild, also re-tagging is done by `gcloud beta container` command.
