### ISSUE TITLE
Unable to get memcached working with wordpress

### ISSUE THREAD

**Issue by jredl-va** [GoogleCloudPlatform/php-docker#149]
@tmatsuo first of all thanks for the helpful guide to get onto the flex runtime: https://wp.gaeflex.ninja/2016/03/14/running-wordpress-on-flex/

However, we are running into an issue with memcache and the current version of the php flex runtime. The PHP startup according to the cloud logs doesn't seem to like the path of memcache.so. Ultimately, this leads to errors when trying to use the memcached / bataches plugins. 

```
[21-Sep-2016 13:19:07 UTC] PHP Warning: PHP Startup: Unable to load dynamic library '/opt/php56/lib/php/extensions/no-debug-non-zts-20131226/memcached.so' - /opt/php56/lib/php/extensions/no-debug-non-zts-20131226/memcached.so: cannot open shared object file: No such file or directory in Unknown on line 0
 {
 metadata: {…}   
 textPayload: "[21-Sep-2016 13:19:07 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/php56/lib/php/extensions/no-debug-non-zts-20131226/memcached.so' - /opt/php56/lib/php/extensions/no-debug-non-zts-20131226/memcached.so: cannot open shared object file: No such file or directory in Unknown on line 0"   
 insertId: "1e89dixg83omuqn"   
 log: "appengine.googleapis.com/app"   
}
```

**Comment by jredl-va** [comment]
And i just noticed that we hadn't enabled memcache.so after reviewing this and the provided examples: https://github.com/GoogleCloudPlatform/php-docker/blob/cbb320250a4ece27892dc626c3bc21ebfeca69fb/testapps/php56_custom/php.ini

**Comment by jredl-va** [comment]
I lied, this bug still exists when enabling memcache.so in our own php.ini. However, we updated to use the php  runtime and memache works as expected. 

Reopening for those trying to use php 5.6 runtime.

**Comment by tmatsuo** [comment]
`memcache.so` or `memcached.so`?

**Comment by jredl-va** [comment]
here is the .ini we were using:

```
extension=bcmath.so
extension=gd.so
extension=memcache.so
zend_extension=opcache.so
memory_limit=1024M
```

**Comment by tmatsuo** [comment]
And what is not working for you now?

**Comment by jredl-va** [comment]
When we enable memcache.so with the PHP 5.6 runtime, we see these errors within the cloud logs of the machine that we have running 

```
[21-Sep-2016 13:19:07 UTC] PHP Warning: PHP Startup: Unable to load dynamic library '/opt/php56/lib/php/extensions/no-debug-non-zts-20131226/memcached.so' - /opt/php56/lib/php/extensions/no-debug-non-zts-20131226/memcached.so: cannot open shared object file: No such file or directory in Unknown on line 0
 {
 metadata: {…}   
 textPayload: "[21-Sep-2016 13:19:07 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/php56/lib/php/extensions/no-debug-non-zts-20131226/memcached.so' - /opt/php56/lib/php/extensions/no-debug-non-zts-20131226/memcached.so: cannot open shared object file: No such file or directory in Unknown on line 0"   
 insertId: "1e89dixg83omuqn"   
 log: "appengine.googleapis.com/app"   
}
```

The php 7 runtime just works.

**Comment by tmatsuo** [comment]
@jredl-va 

Sorry for the late reply. I think you can ignore the warning, and memcached extension is working. If you want to make sure, sshing to the vm and run `sudo docker exec -t -i gaeapp /bin/bash` then run `php -i`.
