### ISSUE TITLE
Can I emulate a storage?

### ISSUE THREAD

**Issue by pedromazala** [GoogleCloudPlatform/php-docker#157]
In GAE i store my files in a storage. Can I emulate a storage in this image?

**Comment by tmatsuo** [comment]
@pedromazala Hi! What do you mean by `emulate`?

**Comment by pedromazala** [comment]
I want to write / read files using gs://, for example. As same how I access a file into google cloud storage.

**Comment by tmatsuo** [comment]
I see. I think it's not this image's responsibility, but we're working on it. Our current plan is to implement Google Cloud Storage stream wrapper in https://github.com/GoogleCloudPlatform/google-cloud-php so that you can use 'gs://' url with `fopen`, `file_get_contents()` etc.

**Comment by pedromazala** [comment]
Ok. One more question.. Can I?

I'm running the image with ```docker run --rm -p 8080:8080 -p 8000:8000 -it -v $(pwd):/var/www image bash```. Is this the best way to run or exists some ```.sh```? I didnt found any docs. 

Thank you :)

**Comment by tmatsuo** [comment]
@pedromazala It depends on your use case. What's your use case for doing that?

**Comment by pedromazala** [comment]
I want to run a specific project. I have one instance running in GAE. 
I'm trying to use this image to have same environment in both... But when i run like this i'm having to run the CMD command manually. (```/usr/share/google_appengine/dev_appserver.py --php_executable_path=/usr/bin/php-cgi --host=0.0.0.0 --admin_host=0.0.0.0 --php_remote_debugging=yes --skip_sdk_update_check=yes .```)

**Comment by tmatsuo** [comment]
I'm a bit confused. Do you want to use `dev_appserver.py`? or do you want to run your application's docker image locally?

**Comment by pedromazala** [comment]
I want to run your application's docker image locally...

**Comment by tmatsuo** [comment]
You may want to have a dockerfile like this:

```Dockerfile
# Dockerfile extending the generic PHP image with application files for a
# single application.
FROM gcr.io/google_appengine/php:latest

# The Docker image will configure the document root according to this
# environment variable.
ENV DOCUMENT_ROOT /app/web
```
You may need to change the environment `DOCUMENT_ROOT` according to your project.

Then you can build it and run:
```sh
$ docker build -t myapp .
$ docker run --rm -p 8080:8080 -it -v myapp 
```
or something. However, when you run the image locally, there will no default service account available for you, so you may want to do something about it.

Also for the most case, you can also run your php application with the php's built-in web server like:

```
$ php -S locahost:8080 -t web
```

**Comment by pedromazala** [comment]
Thank you
