### ISSUE TITLE
Rebuild Image for mongodb.so 1.2.0

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docker#167]
The latest versions of `mongodb/mongodb` require the MongoDB extension (mongodb.so) to be `1.2.0`. The current image uses 1.1.9.

I imagine we just need to build a new image, as the extension gets installed from `pecl`.

**Comment by tmatsuo** [comment]
Is it ok with 1.2.1?

**Comment by bshaffer** [comment]
Yep! That would work great

**Comment by tmatsuo** [comment]
Now it should be 1.2.1
