### ISSUE TITLE
Improve default logging experience on App Engine Flex

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docker#172]
The current idea I have is to have the following in our default nginx.conf:

```
location ~ ^/_ah/health$ {
  access_log off;
  error_log off;
  return 200 'ok';
}
```

This is defined as regex and it's intentional (see the reason below). This directive will suppress all the logs for the health check requests in your `app` category logs.

The Flex log viewer has another log category 'nginx.health_check' and at least you can see the HTTP status there. The nginx will just return 200 'ok' so this log is probably fine.

To override this behavior, you can have a custom `nginx-app.conf` file in your project root:
```
location = /_ah/health {
}
```

Why this works. It works because nginx follows the rules below:

Excerpt from: https://www.linode.com/docs/websites/nginx/how-to-configure-nginx
> Directives are processed in the following order:
>  1. Exact string matches are processed first. If a match is found, nginx stops searching and fulfills the request.
>  2. Remaining literal string directives are processed next. If nginx encounters a match where the ^~ argument is used, it stops here and fulfills the request. Otherwise, nginx continues to process location directives.
>  3. All location directives with regular expressions (~ and ~*) are processed. If a regular expression matches the request, nginx stops searching and fulfills the request.
>  4. If no regular expressions match, the most specific literal string match is used.

**Comment by tmatsuo** [comment]
@bshaffer WDYT?

**Comment by bshaffer** [comment]
This seems great! The downside is if your application is sick, it won't return a 500 because nginx would never actually hit it. But the health check is for the health of the container and not necessarily the application. 

If we document how to override it in the runtime docs, I think this is ok!

**Comment by tmatsuo** [comment]
I think it's ok to say "the default health check handler just returns 200", no?

**Comment by bshaffer** [comment]
We should make it clear that the health check response does not actually touch the application layer. Something like "by default the NGINX web server returns 200 for health checks" or something along these lines.

**Comment by bshaffer** [comment]
@tmatsuo This needs to be implemented before we can go beta.
