### ISSUE TITLE
Flex instance does not report stack traces to stackdriver

### ISSUE THREAD

**Issue by moneal** [GoogleCloudPlatform/php-docker#189]
Errors are being logged to `/var/log/app_engine/app/app-php-error.log` but stackdriver's error reporting is not showing anything. When connected to the server `/var/log/google-fluentd/google-fluentd.log` shows the app-php-error.log being monitored but again stackdriver has nothing. 

Stack traces were being logged correctly on the standard environment but after moving over to flex they don't.

**Comment by JustinBeckwith** [comment]
@tmatsuo I don't think we need to do anything special to support Cloud Errors.  Just like the /var/logs/app_engine stuff, we want to let Cloud Logging do the work here.

**Comment by tmatsuo** [comment]
@moneal We're going to change how to handle logs with #212. Yeah as @JustinBeckwith said the runtime itself should be just stream the logs if possible. Removing the labels now.

**Comment by tmatsuo** [comment]
We are planning to provide some ErrorReporting tools in google-cloud-php. Stay tuned.

**Comment by tmatsuo** [comment]
Now this feature is under alpha testing, the instructions are at:
https://docs.google.com/document/d/126NJTDNctB0zL8dwTo8-9indyWGUXpGkrXCKrHU4b-s

**Comment by moneal** [comment]
New error logging is working great. I'm now seeing alerts and full traces when a error happens on my Laravel app. So nice and can drop a external reporting service :)
