### ISSUE TITLE
Better warning for PHP Version

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docker#206]
[Our current warning](https://github.com/GoogleCloudPlatform/php-docker/blob/5baee599e3591988948698dd9f99255d0b4fccfb/php-nginx/composer.sh#L36) recommends `composer require ~5.6.0`. This should be updated to `composer require 7.1.*`. 

1. The `7.1.*` is more clear which version is being requested, as the tilde (`~`) is a little confusing, and is a convention only used in composer AFAIK.
2. We should still recommend pinning to PHP 7.1, as one day 7.2 will be added.

**Comment by tmatsuo** [comment]
It says something like (replace with your desired version)
