### ISSUE TITLE
Add Phalcon and Cassandra extension

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docker#210]
It would be nice to add the following extensions:

 - [x] [Cassandra](http://datastax.github.io/php-driver/)
 - ~~[New Relic](https://newrelic.com/php)~~
 - [x] [Phalcon](https://phalconphp.com/en/)

**Comment by tmatsuo** [comment]
really needed for beta?

**Comment by bshaffer** [comment]
Up to you!

**Comment by chingor13** [comment]
Phalcon is in #229

**Comment by chingor13** [comment]
Cassandra is in #234

**Comment by chingor13** [comment]
Supporting the NewRelic extension and agent will be much more intensive. Their installer installs upstart scripts which don't run in our docker runtime. We'll have to write something to run their agent via supervisord and would only want to do it if the user needed it.

**Comment by tmatsuo** [comment]
Let's make newreilc separate

**Comment by chingor13** [comment]
These are available with `extension=cassandra.so` and `extension=phalcon.so` in your `php.ini` file.
