### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docker#215]
Hi guys,

We have just released a new version of the runtime, and experimentally started to write a release note at:
https://github.com/GoogleCloudPlatform/php-docker/releases

@cedricziel 
@bshaffer 
@chingor13 

WDYT?

**Comment by chingor13** [comment]
I think it's great to have visibility into when features and bugs are released.

**Comment by cedricziel** [comment]
Great! :+1:

**Comment by tmatsuo** [comment]
Thanks!
