### ISSUE TITLE
[Q] General direction of the image

### ISSUE THREAD

**Issue by cedricziel** [GoogleCloudPlatform/php-docker#22]
I have an important question while I try to bend this image to my needs: What is the feature-complete state of this image?

The heroku buildpack for php is a really great source of inspiration in terms of what is possible and needed for running modern, sophisticated php applications on the platform side of things. I am aware that it may slightly conflict with the "many tiny applications"-paradigm Google drives, but I'm curious if you are willing to go towards that direction with this image as well.

I'd like you to take a look at the compile script of the heroku buildpack for php to see some of the features it detects. (https://github.com/heroku/heroku-buildpack-php/blob/master/bin/compile)

I am aware that I can run a docker image with a heroku buildpack on managed vms - but apart from the general, language specific features, I would also expect AppEngine features from the sandbox to get integrated in the future with this image (CloudSQL with a simple socket). If it wasn't for those, I'd just use the one of the heroku flavoured docker images with managed vms.

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the contributions over the last few days.  Our intent is to build a docker base that's usable with Managed VMs, Kubernetes, or any other platform that supports running containers.  We're certainly planning to make it as easy as possible to connect with other Google Cloud services, and we know we have some work to do with hitting feature parity with Heroku.  The truth is, this repository is about a month old :) We're really just getting started.  We made the choice to build this thing in the open, with hopes that folks would help us decide what's important (after getting the core of the thing put together). So for that - we thank you!  As of today - PHP for Managed VMs is still in the experimental stage.  I'm going to update the README to make sure some of this stuff is a little more clear.

Thanks again!

**Comment by cedricziel** [comment]
Thank you for the comprehensive answer-exactly what I wanted to know! I hope the question didnt sound too pressing - but you know, time is a somewhat limited good-so I just wanted to check if it fits my needs (apart from the fun part) to push the project forward.

I'm well aware of the age of this repository, but we're about to go full steam with AppEngine and I need to make decisions about where we go and how we get there :)

I finally feel some fresh air in AppEngine regarding PHP.  So let me thank you-this repository is really a good sign for me (as is gcloud-php)!

Regarding the experimental stage of PHP with Managed VMs - I see no problem there. I'm fine with running production loads on MVM as long as the platform-vendor is commited to the project ;)

Thanks to you for developing it in the open. Very appreciated!

**Comment by JustinBeckwith** [comment]
Thanks!  We're having a lot of fun with PHP over here right now - I only expect it to get better.  I'm going to go ahead and close this out, but please feel free to keep asking questions, and of course feel free to keep submitting PRs :)
