### ISSUE TITLE
Document how to use this image on GKE

### ISSUE THREAD

**Issue by dlorenc** [GoogleCloudPlatform/php-docker#220]

**Comment by dlorenc** [comment]
We should add a section like this: https://github.com/GoogleCloudPlatform/nodejs-docker#container-engine--other-docker-hosts

**Comment by tmatsuo** [comment]
BTW, how will it work when we move to the runtime builder?

**Comment by dlorenc** [comment]
I imagine at first the builders will be specific to GAE Flex. Users will still be able to build their own image with a standard Dockerfile for other environments.
