### ISSUE TITLE
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docker#224]
Not sure where this is occurring, but on a `7.1` deployment of wordpress, I'm getting the following warning on every PHP command:

```
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
```

My php.ini looks like this:

```
extension=bcmath.so
zend_extension=opcache.so
```

As you can see, `apcu` is not being loaded, so I believe this error is happening in the base runtime.

**Comment by tmatsuo** [comment]
FYI https://github.com/GoogleCloudPlatform/php-docker/releases/tag/2017-03-01-22-10 is live
