### ISSUE TITLE
FreeType support for gd extension

### ISSUE THREAD

**Issue by yukiorii** [GoogleCloudPlatform/php-docker#233]
I read the php-nginx README.md and it says

> `These extensions are compiled as shared (you need to enable with php.ini):`
> `GD (gd; with PNG, JPEG and FreeType support)`

but when i check my app's `php -i`, I see that FreeType for gd extension is not enabled.

Do I have to add anything other than
`extension=gd.so`
in my php.ini to enable the FreeType support?

**Comment by tmatsuo** [comment]
@yukiorii Thanks for the report. Definitely the support was missing. We'll add it soon.

**Comment by tmatsuo** [comment]
We'll release a new runtime soon. I'll close this when it's done

**Comment by tmatsuo** [comment]
Released! https://github.com/GoogleCloudPlatform/php-docker/releases/tag/2017-03-21-20-26
