### ISSUE TITLE
Move config file overrides to build time.

### ISSUE THREAD

**Issue by chingor13** [GoogleCloudPlatform/php-docker#239]
Currently, we move the `nginx-app.conf`, `nginx.conf`, `php-fpm.conf`, `php.ini`, `additional-supervisord.conf`, and `supervisord.conf` files in the entrypoint of the runtime.

These environment variables/config values shouldn't change between build and run time.

We also overwrite the document root in the nginx.conf, but this also shouldn't change between build and run time.

**Comment by garnold** [comment]
[Related](https://github.com/GoogleCloudPlatform/php-docker/issues/295)

**Comment by tmatsuo** [comment]
It's fixed with the new builder pipeline.

**Comment by tmatsuo** [comment]
the builder pipeline
