### ISSUE TITLE
PHP Extensions should be implicitly installable through composer.json

### ISSUE THREAD

**Issue by cedricziel** [GoogleCloudPlatform/php-docker#25]
In order to maintain dependencies to shared PHP extensions, composer packages may define `ext-*` dependencies, like `ext-mbstring`-just like they may define a dependency on a interpreter-version.

The image build-process should be able to read those and add the corresponding `extension` directive to the top-level `php.ini` so that the developer doesn't need to add a `php.ini` file for already explicitly defined dependencies.

**Comment by tmatsuo** [comment]
Yeah, I hope pickle is usable for us:
https://github.com/FriendsOfPHP/pickle

**Comment by cedricziel** [comment]
Interesting project - didnt know that.

I would short-circuit this feature-request for the time being by adapting the heroku buildpack once again, as many shared extensions are already available, but not enabled.

**Comment by tmatsuo** [comment]
Now you can put php.ini with extensions=***.so to enable them.

I agree it is a nice feature to read the composer.json and automate it. What should we do when specified extensions are not compiled?

**Comment by tmatsuo** [comment]
Or probably `composer install` will just fail.

**Comment by bshaffer** [comment]
Yes, I agree. Similar to an unresolvable package version, if the extensions
are not available, an error should be thrown.

**Comment by JustinBeckwith** [comment]
Out of curiosity - which specific extensions are you looking to use?  We're hoping that in the general case most people won't have to install extensions for simple apps.  I see two levels of automation here:

1. Automatically include extensions referenced as ext- in composer.json in the php.ini
2. Actually install extensions into the base image

Does pickle do both of these, or just #2?

**Comment by cedricziel** [comment]
I think the primary goal should be category 1. I actually don't use other extensions very often. Every once in a while I hear from exocit native code, but for those cases, the Docker image can be extended.

If the interpreter doesn't have the extension demanded via composer.json, composer will refuse to install the dependencies from the lock file, which is very transparent in the build output.

**Comment by cedricziel** [comment]
I think regarding (non-shared|third-party) extensions, those might be c implementations for redis and mongo, as well as memcached (provided for 5.6), oAuth, the newrelic agent, blackfire and apcu.

As these are common ones, I think the image should be able to provide them. - What do you think?

**Comment by tmatsuo** [comment]
@cedricziel Yes, we want to pre-compile popular extensions.
