### ISSUE TITLE
Cannot set GitHub OAuth Token

### ISSUE THREAD

**Issue by moneal** [GoogleCloudPlatform/php-docker#251]
I'm having a issue setting a GitHub token to pull a private composer package. The [GitHub oAuth token documentation](https://github.com/GoogleCloudPlatform/php-docker/tree/master/php-nginx#github-oauth-token) says I should be able to set a `COMPOSER_GITHUB_OAUTH_TOKEN` environment variable but this appears to not be available to the ONBUILD script [composer.sh](https://github.com/GoogleCloudPlatform/php-docker/blob/master/php-nginx/composer.sh#L58) when needed.

My app.yaml looks like this:
```
env_variables:
  COMPOSER_GITHUB_OAUTH_TOKEN: 4cb9c8a8048fd02294477fcb1a411...
```

When `composer.sh` runs it does not output any information about the token. If it was set in the environment it would output one of two lines. When `composer install` is ran it uses [--no-scripts](https://github.com/GoogleCloudPlatform/php-docker/blob/master/php-nginx/composer.sh#L83) so  I can't use the `pre-install-cmd` script to register the token.

**Comment by tmatsuo** [comment]
@moneal Thanks for reporting.

@cedricziel I think you have been using that feature. How did you set it?

We have a plan to stop using the `ONBUILD` directive for app engine flexible runtime, and I think it will solve this issue. I will keep you updated for the status of this work.

For a time being, here is an idea for a very dirty workaround.

1. Use the `custom` runtime.
```
gcloud beta app gen-config --custom
```
This will give you a `Dockerfile`, and modified `app.yaml`

Then put a shell script for running `composer` with your github token.
```
#!/bin/sh
mv ${APP_DIR}/composer.json.org ${APP_DIR}/composer.json
# run composer with your github token somehow
```
And add an entry for running this shell script at the end of your Dockerfile.

When deploying, first mv the `composer.json` to `composer.json.org`.
I'm very sorry we only provide this very dirty workaround, but theoretically it should work (I will try using this method by myself and report back).

**Comment by tmatsuo** [comment]
Oh, I think I found an easier way.

1. Install your dependencies locally.
1. Remove `composer.json` before deploy

I think when there's no `composer.json`, it will skip running the most of `composer.sh`, and the `vendor` directory will be preserved. If you need PHP 7.0 or 5.6, you have to do little bit more. Are you OK with PHP 7.1?

**Comment by tmatsuo** [comment]
Probably we should introduce an option to use the uploaded `vendor` directory, without removing `composer.json`.

app.yaml
```yaml
env:flex
runtime: php

runtime_config:
  document_root: web
  preserve_vendor: true
```
or something. @chingor13 WDYT?

**Comment by moneal** [comment]
I'm testing removing the vendor directory right now but I think its going to be a pain to keep using that option. The deployment system is going to have to be a little more complicated. I don't want to upload any dev dependencies but I want to run unit tests before. Previously it was really easy to ignore the vendor directory to speed things up. 

I would like to see the token added to the runtime_config. If `--no-scripts` was removed from the install arguments then I should be able to use the `pre-install-cmd` to manually run the code needed for the token.

**Comment by tmatsuo** [comment]
@moneal 
The workaround should be just for a time being.

When we refactor the build process, we will definitely consider how to add the github oauth token.

**Comment by chingor13** [comment]
If we're going to convert a runtime_config option to an environment variable available at build time, we might as well convert the oauth token from the runtime_config to an environment variable rather than skipping composer install.

**Comment by tmatsuo** [comment]
https://github.com/GoogleCloudPlatform/php-docker/issues/263#issuecomment-300989646
