### ISSUE TITLE
Correct keepalive_timeout of nginx.conf.

### ISSUE THREAD

**Issue by janghwan** [GoogleCloudPlatform/php-docker#267]
In this blog post, short `keepalive_timeout` can cause random 502 problem with gcp load balancers.
https://blog.percy.io/tuning-nginx-behind-google-cloud-platform-http-s-load-balancer-305982ddb340
I wonder if it is still valid. Current `keepalive_timeout`, which is 65, possibly causes problems in production.

**Comment by tmatsuo** [comment]
Thanks for the report. However I haven't seen random 502 problem so far (I see random 502 errors just after deployment, but I think they're separate issue).

**Comment by tmatsuo** [comment]
It's fixed by #348 

Thanks!
