### ISSUE TITLE
Deploy doesn't report bad nginx config.

### ISSUE THREAD

**Issue by iamacarpet** [GoogleCloudPlatform/php-docker#268]
Unfortunately I seem to have had a lot of experience writing nginx config that is broken, but when deploying to Flex it isn't picking up the error with the config and stopping the deployment, although the HTTP health-checks are failing so it doesn't switch to the new version and the error is logged in the stderr log, the command just hangs for a very long time and you have to go check the logs manually.

Speaking with support (Case 12563159), they said for the [example nginx container](https://github.com/GoogleCloudPlatform/appengine-custom-runtimes-samples/tree/master/nginx) the deployment would halt quite quickly with the nginx error message spat out to the console of the deployer, but it looks like because nginx is running via supervisord that functionality doesn't extend to this runtime.

**Comment by tmatsuo** [comment]
@iamacarpet The long time out for the deployment is somewhat intended behavior, for waiting the app to spin up in case the app has long initializing time.

One idea came to mind is to use supervisord's event system to catch the child failure.

**Comment by tmatsuo** [comment]
@iamacarpet Is it ok for you to install Docker on the development machine? Then you can write a test for your config to make sure it works by `gcloud beta app gen-config --custom` and then build the docker image, then run it, make sure it listens to the port, etc.

**Comment by iamacarpet** [comment]
@tmatsuo understood that we need a better local development process to test before something goes live, which is my first priority when I've got everything working on the live environment :).

I do feel like it's something as a user you'll end up hitting some time if you use custom configs, which easily becomes quite a frustration from a usability standpoint when it isn't obvious, as I'll admit, it took me a while to work it out when I first started out with it.

I'm not familiar with it, but supervisord event hooks to catch it sounds great!

**Comment by tmatsuo** [comment]
@iamacarpet 
Sorry, but we haven't implemented the supervisord event cather.

On the second thought, maybe it is enough just to check the configuration file syntax during the build time.

```
/usr/sbin/nginx -t -c /etc/nginx/nginx.conf
```

It will catch most of the failures. WDYT?

**Comment by tmatsuo** [comment]
Released the new image.

Let us know if it works for you.

**Comment by tmatsuo** [comment]
https://github.com/GoogleCloudPlatform/php-docker/releases/tag/2017-09-20-10-53

**Comment by iamacarpet** [comment]
Nice one, thanks @tmatsuo,  that'll save me a lot of time!
