### ISSUE TITLE
Support volume mounting for local development

### ISSUE THREAD

**Issue by garnold** [GoogleCloudPlatform/php-docker#295]
Hello, digging GAE PHP FE thus far!

One challenge we're facing during local development is we'd like to be able to mount our application directory onto the container so we don't need to rebuild when we change files. Something like:

```
docker run --name <name> --publish 8080:8080 --rm --volume=`pwd`:/app <image>:latest
```

The issue is `entrypoint.sh` messes with file permissions and moves files around, causing unexpected changes to our local filesystem. 

[The docs recommend testing applications outside of Docker](https://cloud.google.com/appengine/docs/flexible/php/quickstart#run_hello_world_on_your_local_machine), however that defeats the purpose of using Docker in the first place IMHO.

The fix would be to move the majority of `entrypoint.sh` to `Dockerfile`, except for the Composer stuff. We're happy to rebuild when we change core configuration files like `php.ini` and `nginx*.conf`, but rebuilding when changing application files is tedious.

Thanks for your consideration!

**Comment by chingor13** [comment]
Thanks for the information on your use case! #239 is in progress, but there are internal changes to the GAE deploy process that need to occur first (basically, env variables aren't available at build time).

As far as changing file permissions, that will probably never change as a security precaution.

As a workaround, you could try configure the nginx.conf to use a different directory and mount your code there instead.

**Comment by tmatsuo** [comment]
Also, we have a plan to do some refactoring. Our current plan is to remove the `entrypoint.sh` from some base images. After that, you can just use one of those base images.

**Comment by tmatsuo** [comment]
With the next release, some base images won't have the ENTRYPOINT.

**Comment by tmatsuo** [comment]
Now the following images
* gcr.io/google-appengine/php71
* gcr.io/google-appengine/php70
* gcr.io/google-appengine/php56
don't have ENTRYPOINT.

Give them a try and let us know how it goes.

**Comment by tmatsuo** [comment]
Let me close this. Feel free to reopen

**Comment by garnold** [comment]
Hi @tmatsuo , sorry I missed your previous comment.

Should we be using the versioned images above for development, and the un-versioned image when pushing to Google App Engine? Or do these new images replace the old un-versioned image?
