### ISSUE TITLE
Fix error_log directive

### ISSUE THREAD

**Issue by eflynn** [GoogleCloudPlatform/php-docker#301]
I've noticed nginx always creates an empty file named "log". I've tracked it down to this configuration in `php-base/nginx.conf`:

```
location ~ ^/_ah/health$ {
   access_log off;
   error_log off;
   return 200 'ok';
}
```

The issue is `error_log` does not have an `off` parameter like the `access_log` directive does. To disable the error log, use `error_log /dev/null;`. I'm not sure if disabling the error log has any value in this instance.

See [http://nginx.org/en/docs/ngx_core_module.html#error_log](http://nginx.org/en/docs/ngx_core_module.html#error_log).

#172

**Comment by tmatsuo** [comment]
@eflynn Thanks for reporting. I'm on it.

**Comment by eflynn** [comment]
See #302

**Comment by tmatsuo** [comment]
Thanks for closing this, but actually we haven't released this change to production. We'll close once we release the new images.

**Comment by chingor13** [comment]
This was [released today](https://github.com/GoogleCloudPlatform/php-docker/releases/tag/2017-06-06-13-41).
