### ISSUE TITLE
ext-gmp Plans?

### ISSUE THREAD

**Issue by ConnorVG** [GoogleCloudPlatform/php-docker#303]
Are there any plans, currently, to add support for `php-gmp`?

**Comment by tmatsuo** [comment]
We didn't have a plan, but now we have because of your request.

@chingor13 Can you take a look?

**Comment by chingor13** [comment]
Yep will do. I'm not seeing an major concerns about this extension so maybe we'll just compile it into PHP (rather than as shared). WDYT?

**Comment by tmatsuo** [comment]
SG

**Comment by ConnorVG** [comment]
I think this would be awesome – having to have a `Dockerfile` that simply installs GMP is a bit lame. Shared is 100% fine, there is nothing special about needing it as an external extension (afaict).

**Comment by chingor13** [comment]
The gmp extension should now be available by default in the runtime for new deployments as of [today's release](https://github.com/GoogleCloudPlatform/php-docker/releases/tag/2017-06-06-13-41).

**Comment by ConnorVG** [comment]
Amazing.
