### ISSUE TITLE
Add protobuf extension

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docker#311]
https://pecl.php.net/package/protobuf

- [x] PHP 5.6 - incompatible json implementation - merged, now waiting on 3.3.1 release to PECL
- [x] PHP 7.0
- [x] PHP 7.1 - waiting on 3.3.1 release to PECL

**Comment by chingor13** [comment]
Started a branch [protobuf-extension](https://github.com/GoogleCloudPlatform/php-docker/tree/protobuf-extension)

2 issues which I'll track in the description:

* The extension uses `ext/json/php_json.h`. Our 5.6 runtime does not use the built-in 5.6 version of json, instead using the `jsonc` extension.
* PHP 7.1 does not compile as `EG(scope)` no longer exists. See [Protobuf #3058](https://github.com/google/protobuf/issues/3058). This is fixed and merged in the 3.3.x branch, but a new release will need to be pushed to PECL.

**Comment by chingor13** [comment]
Regarding 5.6: the protobuf extension doesn't actually need that header as it uses a json implementation provided by upb. Created a PR on the protobuf project to remove the include: https://github.com/google/protobuf/pull/3241

**Comment by chingor13** [comment]
Fixed in #317 and released in https://github.com/GoogleCloudPlatform/php-docker/releases/tag/2017-06-23-09-43
