### ISSUE TITLE
[Runtime Builder] Deploy fails with a project with a private repo when you set `enable_stackdriver_integration`

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docker#339]
It uses `composer show` to determine the version of `google/cloud`, and `composer show` fails because of the private repo.

An easy workaround is to create a file named `auth.json` in the project top:
auth.json
```
{
  "github-oauth": {
    "github.com": "your-token-here"
  }
}
```

It's especially confusing when you are using `COMPOSER_GITHUB_OAUTH_TOKEN` for accessing the private repository.

- Option 1: Remove the `COMPOSER_GITHUB_OAUTH_TOKEN` envvar and only allow users to put `auth.json` for accessing the private repo.
- Option 2: When checking the version of `google/cloud`, run `composer config` with the given `COMPOSER_GITHUB_OAUTH_TOKEN` if set

I prefer the option 1 above.

@moneal What do you think?

**Comment by moneal** [comment]
@tmatsuo Option 1 works for me and is working now. Once a official decision is made it would be nice to give a meaning full error if `COMPOSER_GITHUB_OAUTH_TOKEN` envvar is set if going with option 1.

**Comment by tmatsuo** [comment]
@moneal Thanks! We removed that env var in the repo and release a new runtime soon.
