### ISSUE TITLE
Pre-compile the PHP binaries

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docker#34]
It is too slow to compile multiple PHP versions for each Docker build. Can we pre-compile the PHP binaries, upload and download from GCS or somewhere?

**Comment by tmatsuo** [comment]
@sjlangley What do you think?

**Comment by tmatsuo** [comment]
Probably we can use a gcs bucket and upload the PHP binary after test success upon the first compile, and download the binary for all the following build.

**Comment by sjlangley** [comment]
is it a big deal? you only build them once then store the image right?

**Comment by tmatsuo** [comment]
During the application development, it is not a problem at all. The issue here is the development time of this image itself. For example, even when just adding one single new extension, the test runs all of the build, which slows down the development process of this image itself.

If we put the binary somewhere, we can just download it and compile the new extension alone, which will be way faster.

**Comment by cedricziel** [comment]
I'd appreciate binaries as well. The most important facette of this solution for would be that you could potentially switch out/pin patch level versions without having to compile software for an hour upfront.
