### ISSUE TITLE
Migrating from `gcr.io/google-appengine/php` to versioned images

### ISSUE THREAD

**Issue by garnold** [GoogleCloudPlatform/php-docker#353]
(Moving the conversation from https://github.com/GoogleCloudPlatform/php-docker/issues/295 here)

What is the migration path from `gcr.io/google-appengine/php` to the individual versioned images?

**Comment by neildaniels** [comment]
@tmatsuo 

Is there some place where the nuances between the unversioned and versioned are documented or explained?

For example, the unversioned image has the following `OnBuild` steps:
```
                "ARG COMPOSER_FLAGS='--no-scripts --no-dev --prefer-dist'",
                "ENV COMPOSER_FLAGS=${COMPOSER_FLAGS}",
                "COPY . $APP_DIR",
                "RUN chown -R www-data.www-data $APP_DIR",
                "RUN /build-scripts/composer.sh"
```

But the versioned images don't have these steps. 

Besides the lack of `entrypoint` and `OnBuild`, are there more things I should know are "different"? I seemingly need/want to "add" the mentioned `OnBuild` steps; should I also be creating an `entrypoint` file that mostly resembles the file from the unversioned image (minus parts I don't want)?

More succinctly: it's unclear to me _why_ there are versioned images and an unversioned image. Assuming I didn't need to skip the file ownership step of `entrypoint`, I'm not sure why I would choose the versioned images. Is the fact that they "do less" _the reason_ they exist?

(As an aside: I don't intend to use _any_ of these images on App Engine, but on Compute/Container Engine.)

**Comment by tmatsuo** [comment]
@neildaniels There is `ONBUILD` step in `gcr.io/google-appengine/php`, but it makes it hard for people to extend this image.

We decided to create a lighter images with specific version of PHP for App Engine Flex, and they don't have `ONBUILD`. We wanted to make the image as vanilla as possible for making it easier to extend the image.

The current Flex build pipeline is using [this template](https://github.com/GoogleCloudPlatform/php-docker/blob/master/builder/gen-dockerfile/src/templates/Dockerfile.twig) to build the final app image.

I recommend that you can start from there.

**Comment by neildaniels** [comment]
@tmatsuo Awesome! Thanks for the clarification and link to the template!

**Comment by tmatsuo** [comment]
Can we close this now?

**Comment by tmatsuo** [comment]
Closing, but feel free to re-open
