### ISSUE TITLE
Allow overriding composer install flags

### ISSUE THREAD

**Issue by Matan** [GoogleCloudPlatform/php-docker#366]
Hi!

I'd like to be able to override the `composer install` flags passed here: https://github.com/GoogleCloudPlatform/php-docker/blob/master/php-base/build-scripts/composer.sh#L88-L93

I'm creating 3 environments (projects) on GCP namely `dev`, `stage` and `prod`. I need to be able to load the development version of application based on the docker build. Unfortunately there is no way for me to keep the development composer packages as `--no-dev` is hard coded into the build process.

Keep these static:

```
--optimize-autoloader
--no-interaction
--no-ansi
--no-progress
```

Then replace these:

```
--no-dev
--prefer-dist
```

with a build arg defaulted to these sensible values.

Thanks!

**Comment by tmatsuo** [comment]
@Matan Thanks for the feedback.

Which base image do you use, gcr.io/google-appengine/php, or versioned one like gcr.io/google-appengine/php71?

At a first glance, yeah it does make sense to introduce a build arg {`COMPOSER_FLAGS`} defaults to `--no-script --no-dev --prefer-dist` or `--no-dev --prefer-dist` depending on the build pipeline.

**Comment by Matan** [comment]
Hi! I'm using the `gcr.io/google_appengine/php` base image. During build it detects 7.1 requirement correctly.

```
...
---> Running in 9db501558c3e
Detecting PHP version...
Using PHP version: 7.1
Install PHP extensions...
...
```

**Comment by tmatsuo** [comment]
@Matan Thanks you're inheriting from `gcr.io/google_appengine/php`, right? Is it possible to show your Dockerfile?

**Comment by Matan** [comment]
Sure, here it is:

```
# The Google App Engine php runtime is Debian Jessie with PHP installed
# and various os-level packages to allow installation of popular PHP
# libraries. The source is on github at:
#   https://github.com/GoogleCloudPlatform/php-docker
FROM gcr.io/google_appengine/php

# Add our NGINX and php.ini config
ENV DOCUMENT_ROOT=${APP_DIR}/web \
    NGINX_CONF_INCLUDE=conf/nginx.conf \
    PHP_INI_OVERRIDE=conf/php.ini

# Manually create parameters.yml
RUN rm -f ${APP_DIR}/app/config/parameters.yml \
 && mv ${APP_DIR}/app/config/parameters.yml.dist ${APP_DIR}/app/config/parameters.yml
```

My intent is still to remove the manual params generation and let the composer scripts do it. Currently `--no-scripts` is being invoked during build. I see there is a `GOOGLE_RUNTIME_RUN_COMPOSER_SCRIPT` variable I can control for that. But this is minor for now. Getting the dev packages in is more important.

**Comment by tmatsuo** [comment]
@Matan 
Thanks. Do you need to control with the build arg, or is it OK with setting an ENV?

**Comment by Matan** [comment]
What would you suggest? Not sure if I can add a build arg on GCP build trigger. I'll need to check tomorrow.

**Comment by tmatsuo** [comment]
@Matan Yeah it's possible to add a build arg by specifying cloudbuild.yaml. We'll likely support build arg to control the behavior.

**Comment by tmatsuo** [comment]
#368 is merged.

If you want to test the behavior, maybe you can use `gcr.io/php-mvm-a/php:circle-890` (which is built by circleci) for now.

We'll likely release the new image next week.

**Comment by tmatsuo** [comment]
So with the new release, `gcr.io/google-appengine/php` will have a default ARG with `--no-script --no-dev --prefer-dist`.

For example, you can install dev package by passing `--dev` as a build-arg, like:
```
docker build -t myapp --build-arg COMPOSER_FLAGS='--dev' .
```

**Comment by Matan** [comment]
Awesome! Thanks for implementing so quickly!

**Comment by Matan** [comment]
I've switched to `gcr.io/php-mvm-a/php71:circle-890` image and the `COMPOSER_FLAGS` build arg is working as expected. Thanks again!

**Comment by tmatsuo** [comment]
The new image is released. Maybe you can use `gcr.io/google-appengine/php:2017-09-18-11-13`. Closing this issue, but feel free to re-open if you have any issues.
