### ISSUE TITLE
Opcache is not enabled by default.

### ISSUE THREAD

**Issue by janghwan** [GoogleCloudPlatform/php-docker#369]
Opcache extension is not loaded even though the document says it is enabled by default.
i had to add `zend_extension=opcache.so` to `php.ini`  to enable opcache.

**Comment by tmatsuo** [comment]
@janghwan 
Thanks for the report. I would say this is a docs issue. We'll change the documentation.

**Comment by tmatsuo** [comment]
https://cloud.google.com/appengine/docs/flexible/php/runtime

The document updated. Thanks for your report again.

**Comment by janghwan** [comment]
Thanks, but the document I mentioned is this. https://github.com/GoogleCloudPlatform/php-docker/blob/master/php-onbuild/README.md#extensions
And, all the other extensions in the list are enabled by default except Opcache.

**Comment by tmatsuo** [comment]
@janghwan Also fixed that doc. Thanks for the report!

**Comment by tmatsuo** [comment]
@janghwan FYI, we'are going to enable it by default.
https://github.com/GoogleCloudPlatform/php-docker/pull/374
