### ISSUE TITLE
Nginx doesn't detect the upstream https connection

### ISSUE THREAD

**Issue by cedricziel** [GoogleCloudPlatform/php-docker#37]
AppEngines uses HTTPS almost exclusively so it's a good idea to pin HTTPS
to allow applications proper connection detection based on the current protocol.

**Comment by tmatsuo** [comment]
Now finally `env:flex` app has HTTP_X_FORWARDED_PROTO environment variable = 'https' when accessing via https.

I think we can have the following in our nginx.conf
```
map $http_x_forwarded_proto $fastcgi_https {
  default '';
  https on;
}
```
and the following in our fastcgi_param
```
fastcgi_param   HTTPS                   $fastcgi_https;
```

Then $_SERVER['HTTPS'] will be set to 'on'.

**Comment by cedricziel** [comment]
Thanks for the heads-up on this!
