### ISSUE TITLE
Problem on google app engine deploy

### ISSUE THREAD

**Issue by abdounikarim** [GoogleCloudPlatform/php-docker#370]
Hello,  I have a problem on deploy my project (with Symfony) in google app engine. 
This is the error log : 
Step #1: [0mCreating the "app/config/parameters.yml" file
Step #1: [91m> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
Step #1: [0m[91m> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Step #1: [0m[18-Sep-2017 13:23:06 UTC] PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Step #1: Did you forget a "use" statement for another namespace? in /app/app/AppKernel.php:27
Step #1: Stack trace:
Step #1: #0 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(450): AppKernel->registerBundles()
Step #1: #1 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeBundles()
Step #1: #2 /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(69): Symfony\Component\HttpKernel\Kernel->boot()
Step #1: #3 /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(125): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Step #1: #4 /app/bin/console(27): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
Step #1: #5 {main} in /app/app/AppKernel.php on line 27
Step #1: 
Step #1: Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Step #1: Did you forget a "use" statement for another namespace? in /app/app/AppKernel.php:27
Step #1: Stack trace:
Step #1: #0 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(450): AppKernel->registerBundles()
Step #1: #1 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeBundles()
Step #1: #2 /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(69): Symfony\Component\HttpKernel\Kernel->boot()
Step #1: #3 /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(125): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Step #1: #4 /app/bin/console(27): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
Step #1: #5 {main} in /app/app/AppKernel.php on line 27
Step #1: [91mScript Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception
Step #1: [0m[91m
Step #1: [0m[91m 
Step #1: [RuntimeException] 
Step #1: An error occurred when executing the "'cache:clear --no-warmup'" command: 
Step #1: Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle". 
Step #1: Did you forget a "use" statement for another namespace? in /app/app/AppKernel.php:27 
Step #1: Stack trace: 
Step #1: #0 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(450): AppKernel->registerBundles() 
Step #1: #1 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeBundles() 
Step #1: #2 /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(69): Symfony\Component\HttpKernel\Kernel->boot() 
Step #1: #3 /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(125): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
Step #1: #4 /app/bin/console(27): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) 
Step #1: #5 {main} in /app/app/AppKernel.php on line 27 
Step #1: [18-Sep-2017 13:23:06 UTC] PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle". 
Step #1: Did you forget a "use" statement for another namespace? in /app/app/AppKernel.php:27 
Step #1: Stack trace: 
Step #1: #0 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(450): AppKernel->registerBundles() 
Step #1: #1 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeBundles() 
Step #1: #2 /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(69): Symfony\Component\HttpKernel\Kernel->boot() 
Step #1: #3 /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(125): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
Step #1: #4 /app/bin/console(27): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) 
Step #1: #5 {main} in /app/app/AppKernel.php on line 27 
Step #1: 
Step #1: 
Step #1: [0m[91minstall [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...[0m[91m
Step #1: 
Step #1: The command '/bin/sh -c /build-scripts/composer.sh' returned a non-zero code: 1

Can you help me ?

Thanks a lot

**Comment by tmatsuo** [comment]
Maybe you can add an envvar `SYMFONY_ENV` to your `app.yaml`:

```
env_variables:
    SYMFONY_ENV: prod
```

**Comment by abdounikarim** [comment]
it's working 👍 
thanks you so much
