### ISSUE TITLE
Enable Error Reporting by Default

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docker#376]
Essentially, there would be a default prepend file which loads our own logging library in the event one has not already been autoloaded. This file then registers the error handler, exception handler, and shutdown handlers.

```php
// prepend.php

use Google\Cloud\Logging\LoggingClient;
use Google\Cloud\ErrorReporting\Bootstrap;

$autoloadFunc = function () {
    // autoload our own library if it doesn't exist
    if (!class_exists(LoggingClient::class) || !class_exists(Bootstrap::class)) {
        require_once('/sys/cloud_logging_autoloader.php');
    }
    // ensure we are using compatible versions of LoggingClient
    if (version_compare(LoggingClient::VERSION, '1.0.0') == -1 
        || version_compare(LoggingClient::VERSION, '2.0.0') >= 0) {
        return false;
    }
    // populate the psrLogger if it doesn't exist
    if (is_null(Bootstrap::$psrLogger)) {
        $logging = new LoggingClient();
        Bootstrap::$psrLogger = $logging->psrLogger();
    }
    return true
}

// Register all the handlers
register_shutdown_function(function () use ($autoloadFunc) {
    if ($autoloadFunc()) {
        Bootstrap::shutdownHandler();
    }
});
set_exception_handler(function ($e) use ($autoloadFunc) {
    if ($autoloadFunc()) {
        Bootstrap::exceptionHandler($e);
    }
});
set_error_handler(function ($level, $message, $file, $line) use ($autoloadFunc) {
    if ($autoloadFunc()) {
        Bootstrap::errorHandler($level, $message, $file, $line);
    }
});
```

This will automatically send errors to Stackdriver, and as it's prepended it will not conflict if the user wishes to use their own error handler.

**Comment by bshaffer** [comment]
@ryanmats

**Comment by tmatsuo** [comment]
I still have a strong worry about library compatibility.

This is true that, this prepend file will safely install our logging client library.

However, this is not true for all the dependency installed for our logging client library.

For example, `guzzlehttp/guzzle: ^5.3|^6.0` is one of the dependencies of `google/cloud-core`. Let's say we install `guzzlehttp/guzzle` 6.x in our system vendor directory. What happens if the user's app has a strict dependency on `guzzlehttp/guzzle` 5.x? Since we are prepending, the PHP runtime will load `guzzlehttp/guzzle` 6.x before hitting the user code, and it will break.

**Comment by bshaffer** [comment]
This is a great point! In this case, we could employ the same defensive technique as with the Logging Libraries, e.g. check for the existence of dependent libraries and their compatible versions, and return if a conflict exists:

```php
// ensure we are using compatible versions of LoggingClient
if (class_exists(GuzzleClient::class) && version_compare(GuzzleClient::VERSION, '6.0.0') == -1)) {
    return false;
}
```

**Comment by tmatsuo** [comment]
Strictly saying, you have to do that for all the packages under the dependency tree. I don't like that. Also, such a version checking is a composer's responsibility and we shouldn't spend time on re-invent the wheel.

**Comment by tmatsuo** [comment]
Oh wait.

If you run the code snippet above, it will load the `GuzzleClient` from our system vendor dir because we only have enabled our system autoloder. So it doesn't check against the user's dependency.

**Comment by bshaffer** [comment]
@tmatsuo no, it would check `GuzzleClient` *before* including our autoloader!

**Comment by bshaffer** [comment]
Another option would be to have a standalone executable `report-error.phar` which we could call to from the PHP script, which would then be self-contained.

```php
file_put_contents('/tmp/error.txt', (string) $e);
exec('/sys/report_error.phar /tmp/error.txt');
```

**Comment by tmatsuo** [comment]
@bshaffer 
In any case, I'd like to have a design doc

**Comment by bshaffer** [comment]
@tmatsuo will do! Another important point is that this function is only called when an exception is thrown, so no classes are automatically autoloaded unless the application is exiting anyway.

**Comment by tmatsuo** [comment]
Let me close this until decent design doc is available
