### ISSUE TITLE
PHP 7.2 Build Error: "Failed to create symbolic link '/opt/php72/bin/php-enmod'"

### ISSUE THREAD

**Issue by neildaniels** [GoogleCloudPlatform/php-docker#412]
I'm trying to use the PHP 7.2 version of the image and I get a failure starting from the `/build-scripts/composer.sh` script.
**`ln: failed to create symbolic link '/opt/php72/bin/php-enmod': File exists`**

Output from a `docker build` command.
```
// Previous Output Omitted
Reading package lists...
Building dependency tree...
Reading state information...
gcp-php72 is already the newest version.
gcp-php72-apcu is already the newest version.
gcp-php72-apcu-bc is already the newest version.
gcp-php72-cassandra is already the newest version.
// Some output omitted
gcp-php72-stackdriver-debugger is already the newest version.
libsodium18 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ ln -s /opt/php72/bin/php72-enmod /opt/php72/bin/php-enmod
ln: failed to create symbolic link '/opt/php72/bin/php-enmod': File exists
The command '/bin/sh -c /build-scripts/composer.sh' returned a non-zero code: 1
```

I can get this error to occur with a basic Dockerfile such as:
```
FROM gcr.io/google-appengine/php72:2018-01-08-13-41
COPY composer.json $APP_DIR
RUN /build-scripts/composer.sh
```

And a `composer.json` file resembling:
```
{
    "require": {
        "php": "7.2.*"
    }
}
```

I don't encounter this issue using a `php71:2018-01-08-13-41` (PHP 7.1) version of the image.

**Comment by tmatsuo** [comment]
@neildaniels Sorry for the inconvenience and thanks for the report.

We'll work on that, but as a workaround, you can add a ENV

```
ENV DETECTED_PHP_VERSION=7.2
```
Try this and let me know how it goes.

**Comment by neildaniels** [comment]
@tmatsuo That workaround worked. Thanks!
