### ISSUE TITLE
Stackdriver Integration version detection too strict

### ISSUE THREAD

**Issue by chingor13** [GoogleCloudPlatform/php-docker#426]
with an `app.yaml` containing `enable_stackdriver_integration: true`, we do not allow a wildcard version for `google/cloud`, `google/cloud-logging`, or `google/cloud-error-reporting`.

Additionally, if a `composer.lock` file is present, we should respect the locked version when doing our version comparison.

**Comment by tmatsuo** [comment]
Yeah. Right now, it fails all the constraints without the lower bound.
