### ISSUE TITLE
Phalcon for PHP 7.1 & 7.2

### ISSUE THREAD

**Issue by TriPSs** [GoogleCloudPlatform/php-docker#453]
Phalcon supports php 7.2 from release 3.3.

https://github.com/phalcon/cphalcon/blob/master/CHANGELOG-3.3.md#330-2017-12-23

Is it possible to remove the restrictions that Phalcon can only be installed on php 7.0

**Comment by jaitaiwan** [comment]
I'm just leaving a comment here because I can handle this sometime this week.

**Comment by jaitaiwan** [comment]
@TriPSs I've added a pull request in. Hopefully won't be long till feedback/acceptance and a new version is put live.

**Comment by jaitaiwan** [comment]
@sharifelgamal This issue can be closed.
Happy to become a maintainer if there's help needed.

**Comment by TriPSs** [comment]
Thanks @jaitaiwan!
