### ISSUE TITLE
Deprecate PHP 5.6

### ISSUE THREAD

**Issue by jaitaiwan** [GoogleCloudPlatform/php-docker#470]
Now that PHP 5.6 has [reached the end](http://php.net/supported-versions.php) of it's support life-cycle as of the 1st of January, and PHP 7.1 only has 9 months left of security support, I think it's safe to look at removing PHP 5.6 from the builds and perform an upgrade to Ubuntu 18.04 (#451).

I started work on this today, it's involved but doesn't look like too much of a hard change to complete.

**Comment by jaitaiwan** [comment]
I thought I might also note here, that we can make sure we document the php 5.6 images for those people who need legacy support, but considering there will be no more security  updates or feature changes to this version it should be safe to stop builds for it.

**Comment by Rkallenkoot** [comment]
The PHP 5.6 and 7.0 builds are deleted. Old images are still available on the registry

**Comment by donmccasland** [comment]
closing old bug.  5.6 and 7.0 have been deprecated.
