### ISSUE TITLE
Call to undefined method ZipArchive::setEncryptionName()

### ISSUE THREAD

**Issue by Rkallenkoot** [GoogleCloudPlatform/php-docker#485]
**setEncryptionName** / **setEncryptionIndex** have been introducted since PHP version 7.2.0, PECL zip version 1.14.0. But these functions are unavailable in the onbuild image. (I haven't tested the fixed version images yet)

The zip extension is loaded by default and composer.json has PHP 7.2 as requirement.

```
"require": {
        "php": ">=7.2.0",
        ...
}
```

**Comment by Rkallenkoot** [comment]
This is probably because it depends on libzip >= 1.2

**Comment by jaitaiwan** [comment]
Hey @Rkallenkoot, so you're sayign that if libzip is installed php will have those functions? Might be a fairly quick solve.
