### ISSUE TITLE
Sunsetting 7.2 and older

### ISSUE THREAD

**Issue by necrogami** [GoogleCloudPlatform/php-docker#514]
As of the day of writing this we are less then 6 months from the end of security updates for PHP 7.2 this project hasn't updated to 7.3+ and were about to lose security updates for 7.2 and older.

I propose sunsetting 7.2 and older and adding 7.3+ to this project. 

If not is it google's plan to support adding and continuing security patches to older versions of php?

**Comment by sl0wik** [comment]
Begging @donmccasland for this update became my monthly routine. We are waiting since 2018 (https://github.com/GoogleCloudPlatform/php-docker/issues/467). I'm not sure what are the reasons behind.

**Comment by donmccasland** [comment]
7.3 is now in, and being released to public tomorrow.
