### ISSUE TITLE
What's the plan for supporting the GAE services over RPC?

### ISSUE THREAD

**Issue by tomwalder** [GoogleCloudPlatform/php-docker#54]
i.e. Datastore :-)

**Comment by tmatsuo** [comment]
For Datastore, we won't add anything special here. We will use gcloud-php in the future. For now, we're using [the old library](https://github.com/google/google-api-php-client/blob/master/src/Google/Service/Datastore.php) over HTTP/JSON. For other services (mail, taskqueue, etc), the plan is still fluid. Personally I'm leaning towards using open APIs instead of proprietary ones, but we'll need to hear feedback from users.

**Comment by tomwalder** [comment]
Can I compile the protobuf service clients and use them? I assume not because the services themselves will not be exposed to the VMs?

**Comment by bshaffer** [comment]
we should enable the [grpc php extension](https://github.com/grpc/grpc/tree/master/src/php) by default:

```
sudo pecl install grpc-beta
```

**Comment by tmatsuo** [comment]
Yeah let's add it

**Comment by JustinBeckwith** [comment]
Please - we want gRPC to just work if possible

**Comment by tmatsuo** [comment]
#57

**Comment by tomwalder** [comment]
Looks like should compile in?

https://github.com/grpc/grpc/blob/master/src/php/README.md

**Comment by tmatsuo** [comment]
Sorry for not updating here, butit has been merged a while ago

https://github.com/GoogleCloudPlatform/php-docker/pull/62

Thanks anyways!

**Comment by tomwalder** [comment]
Great stuff!

On Saturday, 16 April 2016, Takashi Matsuo <notifications@github.com> wrote:

> Sorry for not updating here, butit has been merged a while ago
>
> #62 <https://github.com/GoogleCloudPlatform/php-docker/pull/62>
>
> Thanks anyways!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/php-docker/issues/54#issuecomment-210917116>
>


-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA
