### ISSUE TITLE
Raise pm.max_children or make it configurable

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docker#65]
The current 5 is too small

**Comment by tmatsuo** [comment]
or should we make it configurable?

**Comment by cedricziel** [comment]
IMHO it should depend on the CPU size of the current box if any :)

**Comment by tmatsuo** [comment]
@cedricziel also machine memory and your app's memory consumption, so automatic calculation is difficult. For a time being, allowing php-fpm.conf override by having the following line

```
include /app/php-fpm.conf
```

may be a short time solution. Users may put php-fpm.conf override in your project directory.

How does it sound?
