### ISSUE TITLE
The builds on travis are flaky

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docker#71]
while builds on jenkins are stable

**Comment by bshaffer** [comment]
@tmatsuo can you define "flaky"? What fails exactly, and what do you think is the cause?

**Comment by tmatsuo** [comment]
I'm pretty certain that inside the docker, a new php-fpm process failed to start. I see random 502 errors on functional test that is running docker -net=host and accessing to it.

**Comment by tmatsuo** [comment]
Sigh... it's not flaky. It's almost always failing now. I will revert the default numbers and introduce `include` directive for overriding values.
