### ISSUE TITLE
Symfony requires function "libxml_disable_entity_loader"

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docker#73]
The function [libxml_disable_entity_loader](http://php.net/manual/en/function.libxml-disable-entity-loader.php) is required in Symfony's XMLFileLoader, and is blacklisted in [our configuration](https://github.com/GoogleCloudPlatform/php-docker/blob/master/php-nginx/php.ini#L938).

Symfony is using the function to make its xml file loading more safe. Wouldn't it be better to call the function (`libxml_disable_entity_loader(true);`) than disable it? Can suhosin be used to disable the entity loader at the php.ini level, thus rendering the function useless?

**Comment by tmatsuo** [comment]
Interesting. I checked whether the entity loader is enabled by default or not, and it seems like it's enabled by default.

So, disabling this function doesn't make any sense. Is there any way to add system wide bootstrap code with PHP?

**Comment by tmatsuo** [comment]
At least we can remove `libxml_disable_entity_loader` from the blacklist.

**Comment by bshaffer** [comment]
We can use [auto_prepend_file](http://docs.php.net/manual/en/ini.core.php#ini.auto-prepend-file) in `php.ini` to include system wide bootstrap.

**Comment by cedricziel** [comment]
auto_prepend_file should be preserved for user operations IMHO.
