### ISSUE TITLE
remove parse_str from blacklist

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docker#79]
We should remove [`parse_str`](http://php.net/manual/en/function.parse-str.php) from the suhosin blacklist.

As @tmatsuo mentioned, if used in a certain way, it's possible for this function to override global variables. However, we need to keep in mind:

1. The function can be used safely when a second argument is supplied
2. The function is very common, as it's the only way (other than rolling your own) to parse a query string.
3. The dangers of using this function require the user to be doing a few other things incorrectly to do damage, namely not providing a 2nd argument to `parse_str` and relying on global scope throughout the app. 

It would be best to remove this function from the blacklist. The best solution would be to disable the function's ability to be used without a second argument, but this is out of scope.

**Comment by tmatsuo** [comment]
Well, I still don't want to remove `parse_str` from the blacklist. The issue here is that there is no way to forbid the dangerous usage.

PHP has been infamous for being insecure for a long time. I don't want anyone use this image with the default setting being hacked.

What about providing alternative library from Packagist?

**Comment by bshaffer** [comment]
The issue is `parse_str` is used in downstream libraries all over the place, so there isn't a way to block this function without breaking... pretty much everything.

The function is only unsafe if used incorrectly. I have never seen it used in the unsafe manner... the behavior is essentially legacy. Also, it should be worth noted this has to be used in global scope for it to have effect:

```php
var_dump($_GET);
// array(1) {
//   ["foo"]=>
//   string(3) "bar"
// }
parse_str('_GET=foo');
var_dump($_GET);
// string(3) "foo"
```

```php
var_dump($_GET);
// array(1) {
//   ["foo"]=>
//   string(3) "bar"
// }
class Foo { 
    function parse_str($str) {
        parse_str($str);
    }
}
$foo = new Foo();
$foo->parse_str('_GET=foo');
var_dump($_GET);
// array(1) {
//   ["foo"]=>
//   string(3) "bar"
// }
```

**Comment by tmatsuo** [comment]
I understand the situation, but I'm still hesitant to remove it. "you have never seen" doesn't guarantee anything. PHP should change the function signature, making the second argument mandatory.

We provide a way to remove it by user, but it's not elegant for now. Maybe we can just improve how to change the blacklist.

**Comment by bshaffer** [comment]
Calling `parse_str` while it is on the blacklist breaks an application and requires x lost time (1-2 hours) for the developer to debug the issue, find the solution, and redeploy. The result is a white screen of death, and the developer has to know to look in the "app" section of Cloud Logging to find the error that relates to suhosin. This is a bad developer experience.

The solution is to *remove the function from the blacklist*. Most developers will just remove all functions from the blacklist (as we ourselves have done) and be angry at Google for the lost time.

This function is not unsafe any more than a call to `mysql` is unsafe. If the user allows SQL injection, calls to `mysql` become unsafe. In the same way, if a user is not sanitizing their inputs and calling `parse_str` without a second argument in global scope, it's unsafe. This is not enough of a reason to block it.

**Comment by tmatsuo** [comment]
I understand that the most of the cases it's safe, but for example, it is still possible that users use a PHP library which uses parse_str in the global scope.
Can we somehow fix the terrible user experience without loosening the default security level?

**Comment by cedricziel** [comment]
@tmatsuo I see your security concerns, but I see no way around them.

**Comment by tmatsuo** [comment]
Alright, I decided to patch PHP and make the 2nd parameter of `patch_str` mandatory, and remove it from the blacklist. @bshaffer Thanks for raising the usability concern!

**Comment by raggi** [comment]
php whack-a-mole. I feel like our path here is perpetual and cyclical. We don't do this in any other runtimes - we don't disable eval in ruby, and so on. I do realize that php has a lot of unsafe APIs, but how can we realistically steward all things that are safe/unsafe and required vs. not in order to write useful programs, or host existing applications/frameworks?

What was the original cause of this re-enablement coming up?

**Comment by tmatsuo** [comment]
re: perpetual and cyclical

It's ok, I'm here for running developers app securely. We will need to always improve.

> We don't do this in any other runtimes 

That's another approach, I don't disagree, but at the same time, we should approach differently for PHP.

The disabled function list is originally comes from the same list for App Engine PHP standard environment. This list is a result from the security review from the Google security team, I think it's somewhat reasonable to start from here.
