### ISSUE TITLE
Native memached session handler broken in PHP7?

### ISSUE THREAD

**Issue by cedricziel** [GoogleCloudPlatform/php-docker#86]
So basically I'm having trouble with the registered native session handler. I run an image with symfony2 3.0 and operating on the session fails silently.

I propose to add an end-to-end test for PHP7 that includes memcached operations.

**Comment by tmatsuo** [comment]
Sorry for the late reply. Yeah I too noticed it but forgot to file an issue. Once the memcache session handler starts to work, we should definitely add the e2e tests.

**Comment by cedricziel** [comment]
BTW - Followup.

I was able to use it through the native Memcached class.

An example on how i wired a memcached handler to my application on appengine flex: https://gist.github.com/cedricziel/cc599be67f816540c608b7658ccd3cf6

**Comment by tmatsuo** [comment]
Good to know the memcached extension is at least working. Thanks for the update :)

**Comment by JustinBeckwith** [comment]
@tmatsuo @bshaffer is this something we need to address for beta?

**Comment by tmatsuo** [comment]
@JustinBeckwith Do we have memcache service available for App Engine Flex? It's slow, but using [the Datastore session](https://github.com/GoogleCloudPlatform/google-cloud-php/blob/master/src/Datastore/DatastoreSessionHandler.php) could be a workaround for many use cases.

**Comment by cedricziel** [comment]
Just to be clear: The memcache service ist available in flex, but this ticket was initially opened because I didn't know how to locate the connection parameters.

I don't know whether the session handler is configured to use it.

The following needs to be done when adressing memcache from a client library:

```php
$host = getenv('MEMCACHE_PORT_11211_TCP_ADDR');
$port = getenv('MEMCACHE_PORT_11211_TCP_PORT');
$cache = new Memcached('myprefix');
$cache->addServer($host, $port);

// $cache is now usable. mind the appengine memcache service doesn't support the "version" command
// many clients use as health check.
```

**Comment by tmatsuo** [comment]
The Flex dropped the out-of-the-box memcache service, so let's close this
