### ISSUE TITLE
Credentials handling

### ISSUE THREAD

**Issue by cedricziel** [GoogleCloudPlatform/php-docker#88]
In my application, I have reached a state where all needed secrets are received from the project-level metadata store - do you think that's a good practice? The description about the metadata store states that it's secure since it's close to local to the compute unit.

Another approach would be to add secrets via environment variables - but it has the implication that I need to write those down to the app.yaml file and thus need to access them on the ci server at deployment time.

Do you prefer one method over the other for AppEngine flex deployments? I guess that's more a RFC than a real issue :)

**Comment by cedricziel** [comment]
Oh btw: In terms of symfony that's very simple done with `gcloud-php`.

```yaml
# app/config/config_prod.yml
imports:
    - { resource: config.yml }
    - { resource: parameters_prod.php }
```

```php
<?php
// app/config/parameters_prod.yml
/**
 * Resolve external parameters from the Compute Engine Metadata Store
 * so we don't need to store sensible information in the VCS.
 * {module}_{environment}_{key}
 *
 * @var \Symfony\Component\DependencyInjection\ContainerInterface $container
 */
$metadataToParameterMap = [
    'database_host'                  => 'module_env_mysql_host',
    'database_port'                  => 'module_env_mysql_port',
    'database_name'                  => 'module_env_mysql_dbname',
    'database_user'                  => 'module_env_mysql_user',
    'database_password'              => 'module_env_mysql_password',
    'service_twitter_client_id'      => 'module_env_service_twitter_client_id',
    'service_twitter_client_secret'  => 'module_env_service_twitter_client_secret',
    'service_google_client_id'       => 'module_env_service_google_client_id',
    'service_google_client_secret'   => 'module_env_service_google_client_secret',
    'service_facebook_client_id'     => 'module_env_service_facebook_client_id',
    'service_facebook_client_secret' => 'module_env_service_facebook_client_secret',
    'service_google_maps_apikey'     => 'module_env_service_google_maps_apikey',
];

// Detect if we're on a AppEngine VM. If not, we're on the CI server and
// set gibberish as params
if (getenv('GAE_VM') === 'true') {
    $metadata = new \Google\Cloud\Compute\Metadata();
    $projectId = $metadata->getProjectId();

    foreach ($metadataToParameterMap as $parameterName => $metadataKey) {
        $container->setParameter($parameterName, $metadata->getProjectMetadata($metadataKey));
    }
} else {
    foreach ($metadataToParameterMap as $parameterName => $metadataKey) {
        if ($metadataKey === 'module_env_mysql_port') {
            $container->setParameter($parameterName, 3306);
        } else {
            $container->setParameter($parameterName, 'localhost');
        }
    }
}
```

It's important to remove the built out cache if composer scripts have already built one. I do this as one of the last steps in a custom `Dockerfile`:

```
RUN rm -Rf /app/var/cache/$SYMFONY_ENV
```

That way the cache and thus the container will be rebuild with the dynamic parameters, when the first health check reaches an application route.

All this saved me a lot of headaches when building and re-building environments and deploying them continously.

**Comment by JustinBeckwith** [comment]
Using the project level metadata service for this purpose should be great.  We want to do more here down the road.  I don't recommend using `app.yaml` for storing env vars... pretty much ever.  It makes a lot more sense to just use something like [dotenv](https://github.com/vlucas/phpdotenv) while keeping the file in your `.gitignore`.

**Comment by cedricziel** [comment]
Thx for your answer-very appreciated!

I've used dotenv in a number of projects and it's fine. One concern that has grown over time is that the container contains (hehe, bingo!) the secrets as well when using something like dotenv or hardcoded credentials plus the build environment needs to have a hold on them. So everybody that has a copy of the container basically has all the secrets as well and that could quickly ruin a day.

Since AppEngine flex orchestrates the minion vms with a kubelet and I suppose there's a Kubernetes cluster in the room. - Is it planned to max out the possibilities there a little more? Recent versions of Kubernetes have support for secrets; I think that could be a great possibility to plug in secure environment variables.

**Comment by JustinBeckwith** [comment]
That's a very good point :) We absolutely want to add something like this to Managed VMs - it's on the list!

**Comment by cedricziel** [comment]
Sounds awsome!
