### ISSUE TITLE
Remove PGP key import script

### ISSUE THREAD

**Issue by raggi** [GoogleCloudPlatform/php-docker#97]
It's not being used, and should be removed.

**Comment by tmatsuo** [comment]
It's actualy used at:
https://github.com/GoogleCloudPlatform/php-docker/blob/d7061914bd9506cb731d1f9d964fdf249b892b2c/php-nginx/Dockerfile#L66

**Comment by raggi** [comment]
The result of that script being run is not being used. We're not pulling any packages from nginx managed apt sources.

**Comment by cedricziel** [comment]
The scripts for compiling nginx and the php sources download the signatures and verify them against the imported keys.

Example: https://github.com/GoogleCloudPlatform/php-docker/blob/master/php-nginx/build-scripts/build_php70.sh#L25

**Comment by tmatsuo** [comment]
Yes, it is used for verifying the source tarballs.

**Comment by raggi** [comment]
I missed that, my apologies.

So there's another issue here which is that we're trusting those keys globally and then using that trust to assert the package signatures. As we're not verifying who signed the package, we don't know if it came from the canonical authors (i.e. an nginx key breach would threaten the php verification).

We also import far too many of the nginx developer keys, we only need to import the package signing key: http://nginx.org/keys/nginx_signing.key

If any of the nginx developers (for example) had a key breach, we likely wouldn't notice here.

**Comment by raggi** [comment]
Oh we're also not establishing a chain of trust for the keys received from the keyserver.

Lets import validated keys in ascii armor to the repo and not use a key fetch on every build.
And lets verify that the key we expect is the key that was used to sign the packages.

**Comment by tmatsuo** [comment]
The signing key is `7BD9BF62`, but actually the source tarball (asc) is signed with `A1C052F8`. 

Do you want to import all the ascii keys listed at:
http://nginx.org/en/pgp_keys.html

The issue is the site's https address gives me an ssl cert error.

**Comment by raggi** [comment]
Why do you trust A1C052F8 when the site does not say it's used for releases?

What is the history of that key?

Did you file a bug?

**Comment by tmatsuo** [comment]
It's initially done by @sjlangley 

http://nginx.org/en/security_advisories.html
says:

```
Patches are signed using one of the PGP public keys.
```

**Comment by tmatsuo** [comment]
The nginx website doesn't work with https, which I think is a bigger problem. I will contact them asking to fix it.

**Comment by tmatsuo** [comment]
I asked them to use the correct cert and now it's working well :)
https://nginx.org/en/pgp_keys.html

@raggi Do you still want to add the keys to the repo?

**Comment by raggi** [comment]
We still need to implement a way to verify that we fetched the correct key, and then verify that the correct key was used for signing. The present code does neither.

**Comment by tmatsuo** [comment]
What do you propose?

**Comment by raggi** [comment]
a or b or c

a) Use signed packages with a package system that verifies those signatures correctly (e.g. an official ppa/debian mirror)
b)
  i) Commit the correct keys to the repo and verify that the correct keys are used for signing (parse the output of gpg verify)
  ii) Commit a cryptographically sound verification string for the exact package you expect (e.g. add shasum to the dockerfile and verify it prior to build, then you can drop all the pgp stuff)
c) Add manually verified source packages directly to the repo
