### ISSUE TITLE
Integrate with the vm image log rotation instead of cron inside container

### ISSUE THREAD

**Issue by raggi** [GoogleCloudPlatform/php-docker#98]
The system image should be rotating logs in /var/log/app_engine. We should integrate with that, and make any file path changes necessary for that to work.

**Comment by tmatsuo** [comment]
If the image takes care of the log rotation, it will be awesome. I'm wondering where I can read more about it.

**Comment by JustinBeckwith** [comment]
@andrewsg should have state here

**Comment by JustinBeckwith** [comment]
The runtime contract no longer respects writing into the `/var/log/app_engine` - everything is managed via docker and stdout/stderr.  @tmatsuo - can you take a look and make sure this isn't relevant?
