### ISSUE TITLE
Stop removing the vendor directory

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docker#99]
I'm considering to stop removing the `vendor` directory during the bulld.

@cedricziel FYI

**Comment by cedricziel** [comment]
Thx for the ping - IMHO that's a two sided sword, but would make for better layer caching.

My thoughts are the following:

PRO (keep the vednor dir from the build host):
* caching. A warmed vendor directory is nice for build times

CONTRA ():
* users could have libraries in the vendor directory that do not belong to the current platform in cases the outer environment isnt congruent to the inner environment (the container one). That would cache garbage that would be frozen in the layer through the `COPY` directive
* what about manually changed files in the vendor directory? Composer checks the integrity on install, but afaik only if the vendor directory is empty or nonexistent

My proposal is actually something in the middle:
`ONBUILD COPY` composer.json and composer.lock (https://github.com/heroku/docker-php/blob/master/Dockerfile#L71) then `composer install --no-scripts` to populate the global composer cache in the image. That way, there's a nice caching layer in place until either one of those files change. Now we can keep removing the vendor directory as the packages will be resolved through the global cache.

**Comment by tmatsuo** [comment]
@cedricziel 

Re: platform deps
We're running `composer install` and it should fix it.

Re: manually changed files in the vendor directory?
It's kind of intentional to keep them.

Anyways, your proposal looks good too. I'll try them.

**Comment by tmatsuo** [comment]
I'm trying to implement it, but I get a feeling that it will require composer based app because

```
ONBUILD COPY composer.lock composer.json ${APP_DIR}
```

This line will fail if there are no such files.

I also want to support apps without composer.json (like WordPress!). What do you think?
